import { Fragment, Component } from 'react';
import {
  EuiCode,
  EuiCodeBlock,
  EuiErrorBoundary,
  EuiSpacer,
  EuiTab,
  EuiTable,
  EuiTableBody,
  EuiTableHeader,
  EuiTableHeaderCell,
  EuiTableRow,
  EuiTableRowCell,
  EuiTabs,
  EuiText,
  EuiTextColor,
  EuiTitle,
  EuiLink,
  EuiFlexGroup,
  EuiFlexItem,
  EuiButton,
  EuiButtonEmpty,
  EuiButtonIcon,
  EuiFlexGrid,
  EuiPanel,
  EuiIcon,
  EuiButtonToggle,
  EuiAccordion,
  EuiForm,
  EuiFormRow,
  EuiFieldPassword,
  EuiFieldText,
  EuiTextArea,
} from '../../../../src/components';

const scope = {
  EuiFieldPassword,
  EuiFieldText,
  EuiTextArea,
  EuiFormRow,
  EuiForm,
  EuiAccordion,
  EuiButtonToggle,
  Component,
  EuiCode,
  EuiCodeBlock,
  EuiErrorBoundary,
  EuiSpacer,
  EuiTab,
  EuiTable,
  EuiTableBody,
  EuiTableHeader,
  EuiTableHeaderCell,
  EuiTableRow,
  EuiTableRowCell,
  EuiTabs,
  EuiText,
  EuiTextColor,
  EuiTitle,
  EuiLink,
  EuiFlexGroup,
  EuiFlexItem,
  EuiButton,
  Fragment,
  EuiButtonEmpty,
  EuiButtonIcon,
  EuiFlexGrid,
  EuiPanel,
  EuiIcon,
};

export default scope;
